[project]
name = "weather-telegram-bot"
version = "0.1.0"
description = "Бот для получения прогноза погоды в Telegram"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings==2.9.1",
]
